site_name: ValkeyJSON - a JSON data type for Valkey
site_url: https://valkey.io
site_favicon: 'images/favicon.png'
repo_url: https://github.com/goodform/valkey-json
repo_name: goodform/valkey-json
theme: material

extra:
  palette:
    primary: 'indigo'
  logo: 'images/logo.svg'
  social:
    - type: 'github'
      link: 'https://goodformcode.com/valkey-json'

markdown_extensions:
  - codehilite

pages:
    - 'Quickstart': 'index.md'
    - 'Commands': 'commands.md'
    - 'Path syntax': 'path.md'
    - 'Performance': 'performance.md'
    - 'RAM usage': 'ram.md'
    - 'Developer notes': 'developer.md'

google_analytics:
    - 'UA-92003007-8'
    - 'auto'
